### ISSUE TITLE
GET single row 

### ISSUE THREAD

**Issue by Sujith105** [jeevatkm/excelReader#2]
Is the possible to get only row (possible header)in poi event model without looping entire rows ?.

**Comment by jeevatkm** [comment]
do you mean 'getting only header row from every worksheet not data rows'?  or can you elaborate in detail.

**Comment by jeevatkm** [comment]
Added sheetName value to the ExcelSheetCallback.java startSheet method and deployed SNAPSHOT into [Maven repo](https://oss.sonatype.org/content/repositories/snapshots/com/myjeeva/poi/excelReader/1.3-SNAPSHOT/)

You can try now!

**Comment by Sujith105** [comment]
yes...i want to get only the particular row

**Comment by jeevatkm** [comment]
Released `v1.3` to maven central.
