### ISSUE TITLE
ExcelWorkSheetRowCallbackHandlerTest Fails When Using 1.3-SNAPSHOT

### ISSUE THREAD

**Issue by opticyclic** [jeevatkm/excelReader#3]
If I run ExcelWorkSheetRowCallbackHandlerTest from master it outputs the row details to system out.
If I copy and paste the test class into a new project and add 1.3-SNAPSHOT as a dependency the callback is never called and the row details are not printed to system out.

**Comment by jeevatkm** [comment]
I'm closing it. Released `v1.3` to maven central.
